services:
  web:
    build: .
    volumes:
      - ./app/note-app:/app/note-app
    working_dir: /app/note-app
    ports:
      - 3000:3000
    command: yarn run dev
    tty: true
    stdin_open: true
